import fs from "node:fs/promises";
import path from "node:path";

const periodStart = "2026-06-01";
const periodEnd = "2026-06-07";
const executedAt = "2026-06-08 16:43:43 CST";
const reportTitle = "SEO 週報｜SHOPLINE｜2026-06-01 至 2026-06-07";
const runId = "weekly-seo-20260601-20260607-20260608-164343";
const outDir = "/Volumes/T7/Codex AI Agent";
const outPath = path.join(outDir, `${periodStart}_${periodEnd}_週報.xlsx`);

const weeklyHeaders = [
  "week_start","week_end","summary","top_opportunity","top_risk","organic_clicks_change","organic_sessions_change","conversions_change","recommended_actions","next_review_date","競爭對手比較","競品內容缺口","競品AI搜尋觀察","title","executed_at","data_quality","gsc_summary","ga4_summary","ahrefs_summary","screaming_frog_summary","workduo_summary","competitor_comparison","status","executive_summary","keyword_cluster_summary","search_performance_summary","technical_seo_summary","internal_linking_summary","content_recommendation_summary","competitor_ai_summary","action_count","p1_action_count","validation_status"
];

const weeklyRow = [
  periodStart,
  periodEnd,
  "本週最大問題是商業核心頁 CTR 與內容承接仍弱；最大機會是把高曝光頁與比較型內容一起放大；技術面已從大規模錯誤回到可管理狀態。",
  "優先拉升 /about/pricing、/about、/showcase、/online-store/features 與比較型內容，這些頁已有曝光或商業意圖，最接近帶來轉換改善。",
  "競品在 AI citation 與工具型 / 教學型內容仍領先；若只修技術不補比較頁與引用友善內容，非品牌成長會再落後。",
  "Sampled top-page GSC clicks down sharply WoW; homepage 1123 -> 369 and pricing 83 -> 35.",
  "Organic Search proxy users +0.9% and visits flat at 1,880 via Ahrefs Web Analytics.",
  "GA4 native key events unavailable this run; conversion delta pending connector restore.",
  "P1 CTR sprint on five money pages; P1 fix 68 short meta descriptions; P1 reduce 22 slow pages; P1 add links to 38 weak-linked pages and 5 sitemap-missing pages; P1 refresh comparison cluster for 電商平台 / 網站架設; P2 fix structured data on 96 pages; P2 build AI citation-ready proof pages; P2 refresh FAQ/support intent pages; P2 audit 3XX/redirect chain leftovers; P2 prune or noindex low-value news pages; P2 restore GA4 key events; P2 expand Workduo competitor monitoring.",
  "2026-06-15",
  "Ahrefs TW organic traffic: 91app.com 51.5k > cyberbiz.io 34.1k > shopline.tw 32.6k > bvshop.tw 28.5k > shopify.com/tw 14.1k > meepshop.com 3.6k. Keyword breadth: Cyberbiz 3,502 > SHOPLINE 2,455 > 91APP 1,758.",
  "Cyberbiz wins with asset-size, free-image, Reels and short-video tutorials; Shopify wins with generators and calculators; BVSHOP wins with platform-comparison and POS explainers. SHOPLINE still lacks a strong main-site comparison hub plus tool-like assets.",
  "Workduo competitor citations outpace owned domains: cyberbiz.io 3.16%-4.12%, bvshop.tw 3.68%-4.99%, 91app.com 1.75%-1.84% versus shopline.tw 2.24%-4.35% and blog.shopline.tw 1.07%-1.52%; negative sentiment themes were empty this week.",
  reportTitle,
  executedAt,
  "Available: Ahrefs GSC, Ahrefs Web Analytics, Ahrefs Site Audit, Ahrefs Site Explorer, Workduo metrics/citations. Missing: native GA4 keyEvents and Screaming Frog MCP. Technical section uses Ahrefs Site Audit fallback by design. 91APP required apex-domain retry because www target returned zero traffic.",
  "GSC current week: homepage 369 clicks / 3,949 impressions / CTR 9.34%; pricing 35 / 1,816 / 1.93%; showcase 14 / 1,685 / 0.83%; about 7 / 1,810 / 0.39%; online-store/features 0 / 1,382 / 0.00%. Position buckets: 1-3 contributes 93.5% of clicks, while positions 4-20 still hold 679 impressions with almost no clicks.",
  "GA4 MCP unavailable. Ahrefs Web Analytics proxy for Organic Search: 1,718 users, 1,880 sessions, 2,947 pageviews, 68.7% bounce, 227s avg session duration. Landing pages with strongest dwell: /about/pricing 510s, /showcase 356s; keyEvents unavailable.",
  "Site Explorer shows mixed momentum: homepage traffic 13.7k (-13%), pricing 864 (-48%), about 886 (-11%), while stories/blog assets such as url-shortener-tools (+152%), instagram-image-sizes (+3389%), what-is-pos (+1255%) and usp explainer (+1224%) are winning non-brand demand.",
  "Screaming Frog MCP not available; using Ahrefs Site Audit fallback. Health score 98 on 103 crawled URLs. Resolved from last run: double-slash URLs and hreflang-to-non-canonical dropped to 0 current affected URLs. Remaining material issues: meta description too short 68, structured data rich-result validation 96, slow page 22, pages with only one dofollow incoming internal link 38, indexable pages not in sitemap 5.",
  "Workduo platform metrics on 2026-06-01: SHOPLINE visibility 0.8667 / SOV 0.2342, Shopify 0.7111 / 0.1922, Cyberbiz 0.7111 / 0.1922, 91APP 0.5000 / 0.1351. Owned citation share improved on 2026-06-05 for shopline.tw to 4.35%, but competitor domains still win aggregate citation volume.",
  "SHOPLINE is now technically stable enough to shift focus back to SERP CTR, comparison content and AI-citable proof assets. Cyberbiz leads breadth and citation-friendly how-to content; 91APP leads traffic with brand + AI explainer assets; Shopify leads with free tools and generators.",
  "completed",
  "最大問題：高曝光頁 CTR 與商業意圖承接仍弱，尤其 /about、/showcase、/online-store/features、/about/pricing。最大機會：比較型與工具型內容可以同時帶動非品牌搜尋與 AI citation。最大風險：競品在教學資產、生成器、AI explainers 與 citation share 領先。P1 5 項、P2 7 項、P3 0 項，本週建議以 CTR、速度、內鏈、比較內容四條線並行。",
  "Cluster 1 電商平台 / 開店平台 / 網站架設 | intent=Commercial | core=電商平台、開店平台、官網架設 | pillar=/bulid-website-platform-compare and main-site comparison hub gap | support=/about/pricing,/online-store/features,/what-is-ecommerce-and-how-to-succeed | gap=91APP/Cyberbiz/Shopify/BVSHOP 對比頁與 pricing FAQ | internal links=from homepage/about/pricing/showcase to comparison hub. Cluster 2 POS / OMO / 智慧零售 | intent=Commercial | pillar=/pos/features | support=/what-is-pos,/solutions/omo,/shopper-app | gap=POS ROI, hardware, retail workflow FAQ | internal links=from pricing, solutions and industry pages. Cluster 3 AI / MCP / 零售 AI | intent=Informational+Commercial | pillar=/ai | support=/news/shopline-app-store,/whitepaper/news assets | gap=AI retail use case, MCP setup, proof statistics | internal links=from homepage and content wins. Cluster 4 社群導購 / 團購 / 直播 | intent=Commercial | pillar=/group-buying | support=/social-commerce,/social-commerce/instagram-live | gap=導購 SOP, conversion benchmarks, FAQ schema | internal links=from shopper-app and solutions. Cluster 5 品牌信任 / 方案 / 客服 | intent=Navigational+Commercial | pillar=/about,/about/pricing | support=/faq/about,/faq/overview,/showcase | gap=pricing objections, migration and support trust blocks | internal links=from homepage, pricing and FAQ cross-links.",
  "High-impression low-CTR pages: /online-store/features 1,382 impressions CTR 0.00% pos 1.25; /about 1,810 impressions CTR 0.39% pos 1.43; /showcase 1,685 impressions CTR 0.83% pos 1.19; /faq/about 1,463 impressions CTR 0.27% pos 1.11; /about/pricing 1,816 impressions CTR 1.93% pos 1.54. Position 4-20 opportunities from GSC current sample are limited, but Ahrefs organic keywords still show commercial gaps around 電商平台, 網站, 官網架設 and ecommerce explainers. Query cannibalization remains mostly branded: 'shopline' spans 22 URLs, 'shopline後台' spans 2 URLs, 'shopline 方案' spans 6 URLs; align homepage, pricing and FAQ intent boundaries. Organic Search proxy totals: 1,718 users, 1,880 sessions, 2,947 pageviews; strongest landing-page depth on /about/pricing and /showcase; GA4 keyEvents unavailable.",
  "Core Web Vitals / speed: slow page 22 | sample URLs=https://shopline.tw/about/pricing, https://shopline.tw/shopper-app, https://shopline.tw/online-store. Crawl / indexability: indexable page not in sitemap 5 | sample URLs=https://shopline.tw/ai, https://shopline.tw/corp-social-responsibility, https://shopline.tw/news/shopline-cashback. Robots / noindex / canonical: robots.txt not accessible 2 crawl attempts; current canonical blockers are materially lower and hreflang-to-non-canonical is now 0 active affected URLs. Duplicate title/meta/H1/content: meta description too short 68 | sample URLs=https://shopline.tw/, https://shopline.tw/about/pricing, https://shopline.tw/about; H1 missing 1 active indexable URL. 404 / redirect / broken links: 3XX redirect 3 and redirect chain 1 remain; no material 4XX/5XX sitemap issues detected. Structured data / hreflang / sitemap: Google rich-result validation error 96 | sample is broad sitewide; x-default hreflang missing 82; indexable pages not in sitemap 5. Screaming Frog unavailable, so this module uses Ahrefs Site Audit fallback.",
  "New pages that should receive links from older pages: /ai, /news/shopline-cashback, /news/shopline-payments-mpi, /online-store/shop-builder-crowdfunding, /corp-social-responsibility. Older pages that should link back to new commercial/support pages: homepage, /about/pricing, /solutions, /shopper-app, /online-store/features. Hub pages needing new links: homepage should add comparison hub, AI proof page and POS explainer links; pricing should link to POS, OMO and migration/comparison pages; showcase should link to vertical solution pages. Weakly linked or near-orphan pages from Site Audit issue count 38 include /ai, CSR and news assets; prioritize URLs tied to AI, payments, industry pages and comparison content because they have commercial value or citation potential.",
  "Refresh: /about, /showcase, /faq/about, /online-store/features, /online-store-setup for clearer SERP intent and proof blocks. Expand: /bulid-website-platform-compare, /group-buying, /solutions/omo, /ai with comparison FAQs, benchmarks and schema. Consolidate: overlap between /about and /faq/about, and between support/pricing explanation fragments, to reduce branded cannibalization. Split: create dedicated 91APP / Cyberbiz / Shopify comparison pages instead of forcing all intent into a single broad comparison article. Prune/noindex: low-value news pages with zero traffic and no strategic citation value, especially stale press releases that neither rank nor support trust journeys.",
  "Ahrefs competitor snapshot: 91app.com leads traffic at 51.5k, driven by brand + AI explainer pages like Claude AI and Gemini; cyberbiz.io leads keyword breadth at 3,502 and refdomains at 6,615, with top pages around FB image sizes, free images, Reels and short-video marketing; bvshop.tw wins with platform-comparison and POS explainers plus strong AI citation share; Shopify TW wins with utility pages like business-name generator, slogan maker and policy generator. Workduo AI: on 2026-06-01 SHOPLINE led tracked entity visibility at 0.8667, but competitor citation domains still outnumber owned citations on multiple days; negative sentiment themes were empty, so the main AI gap is absence, not negativity. Three competitor content angles to borrow next: free tools / generators; social-media asset-size templates; AI / retail explainer pages with citation-friendly facts and FAQs.",
  12,
  5,
  "warning"
];

const actionHeaders = [
  "created_date","priority","category","url","query_or_keyword","issue","evidence","recommendation","expected_impact","status","owner","due_date","done_date","result_note","problem","impact","expected_outcome_range","how_to","priority_score","business_impact","traffic_opportunity","conversion_relevance","technical_risk","effort","confidence"
];

const actions = [
  ["2026-06-08","P1","CTR","https://shopline.tw/about/pricing","電商平台, 開店平台, shopline 費用","High-impression money pages underperform CTR despite top-3 rankings","/about 0.39% CTR on 1,810 impressions; /showcase 0.83% on 1,685; /online-store/features 0.00% on 1,382; /about/pricing 1.93% on 1,816","Run a SERP CTR sprint across /about/pricing, /about, /showcase, /faq/about and /online-store/features with new title/meta, trust proof and FAQ blocks","Lift qualified clicks on existing rankings","open","","2026-06-15","","","Existing visibility is concentrated on branded/commercial pages but snippets do not convert impressions into clicks.","Higher CTR on these pages should lift more qualified traffic without waiting for new rankings.","CTR +0.3-0.8pp; Organic sessions +5-10%","Rewrite title/meta by intent, add pricing objections and migration FAQ, align H1 and intro copy with search demand.","12","5","4","4","1","2","0.83"],
  ["2026-06-08","P1","Content SEO","https://shopline.tw/","meta descriptions","68 indexable pages still have short meta descriptions, including core pages","Site Audit: meta description too short 68; samples include homepage, /about/pricing, /about","Fix short meta descriptions in batches, starting with pages that already have traffic or commercial intent","Improve CTR and message-match at scale","open","","2026-06-15","","","Meta descriptions are still too generic or short on many pages after technical cleanup.","A scaled metadata pass improves both CTR and consistency across key landing pages.","CTR +0.2-0.6pp; Organic sessions +3-7%","Create template variants by page type, prioritize high-traffic pages first, QA against SERP truncation and intent.","13","5","4","4","2","2","0.8"],
  ["2026-06-08","P1","Technical SEO","https://shopline.tw/about/pricing","site speed","22 URLs remain in the slow-page bucket after the larger technical recovery","Site Audit: slow page 22; samples include /about/pricing, /shopper-app, /online-store","Reduce slow-page load cost on high-value templates before the next crawl","Protect conversion and UX on money pages","open","","2026-06-15","","","The site is much healthier overall, but high-value landing pages still appear in the slow-page set.","Speed fixes now have a cleaner environment to show impact and reduce bounce on conversion pages.","Organic sessions +3-6%; Key landing bounce rate -3-8%","Compress heavy assets, defer non-critical scripts, review template payload and rerun crawl on affected templates.","12","4","3","4","3","2","0.77"],
  ["2026-06-08","P1","Internal Linking","https://shopline.tw/ai","AI, MCP, comparison pages","38 pages have only one dofollow incoming internal link and 5 indexable pages are missing from sitemap","Site Audit weak-link samples: /ai, CSR, cashback news, MPI news, crowdfunding page; sitemap-missing issue count 5","Strengthen internal links and sitemap coverage for weakly-linked strategic pages","Help indexing, discovery and citation-eligible pages earn authority faster","open","","2026-06-15","","","Important strategic pages are too isolated to accumulate internal authority or crawl attention.","Better internal linking is the fastest lever for pages that are already published but under-discovered.","Indexable pages +5-10; Organic sessions +3-8%","Add links from homepage, pricing, solutions and showcase hubs; add missing URLs to sitemap; verify in next crawl.","13","4","4","3","4","2","0.84"],
  ["2026-06-08","P1","Content Gap","https://blog.shopline.tw/bulid-website-platform-compare/","電商平台, 官網架設, 網站","Commercial comparison demand exists, but SHOPLINE lacks enough dedicated comparison assets on main site","GSC query opportunity: 電商平台 and 開店平台; competitor wins: BVSHOP article 72 ranks #1 for 電商平台; Shopify tool pages and Cyberbiz tutorials capture adjacent demand","Turn comparison intent into a hub + dedicated competitor pages for 91APP, Cyberbiz and Shopify","Capture bottom-funnel non-brand demand","open","","2026-06-15","","","Commercial-intent searchers still need clearer feature, pricing and fit comparisons from SHOPLINE.","A focused comparison cluster can convert existing awareness into evaluation-stage traffic and lead intent.","Organic sessions +8-15%; CTR +0.3-0.7pp","Refresh the existing comparison article, split out competitor-specific pages, add tables, pricing FAQs and strong internal links from pricing/homepage.","12","5","5","4","1","3","0.79"],
  ["2026-06-08","P2","Structured Data","https://shopline.tw/","rich results","96 URLs still have Google rich-result validation issues","Site Audit: structured data rich-result validation error 96","Repair schema validation across templates that support FAQ, organization and product/service snippets","Increase rich-result eligibility and citation quality","open","","2026-06-22","","","Template-level schema issues remain one of the largest sitewide technical buckets.","Cleaner structured data supports SERP enhancements and AI extraction quality.","Rich results coverage +10-20; CTR +0.1-0.4pp","Audit template schema, remove invalid properties, retest in Rich Results Test and resubmit priority URLs.","10","3","3","3","4","3","0.75"],
  ["2026-06-08","P2","AI SEO","https://shopline.tw/ai","AI retail, MCP, ecommerce AI","Owned domains still trail competitor citation volume even when visibility is strong","Workduo owned citation share: shopline.tw 2.24%-4.35%; competitor citation leaders include cyberbiz.io, bvshop.tw and blog.easystore.co","Build citation-ready AI proof pages with data points, FAQ blocks and clear sourceable statements","Grow AI answer mentions and citations","open","","2026-06-22","","","SHOPLINE appears in AI answers, but too often competitors provide the quoted supporting source.","Citation-ready pages can convert visibility into reusable evidence across ChatGPT, Gemini and AIO.","AI citations +10-25%; Brand mention share +3-8%","Create AI retail proof pages, embed FAQ/schema, cite internal whitepapers and link them from /ai and solution hubs.","10","4","3","3","2","2","0.74"],
  ["2026-06-08","P2","Refresh","https://shopline.tw/faq/about","shopline 是什麼, 客服, support","Support and brand-trust pages overlap and under-serve search intent","/faq/about CTR 0.27% on 1,463 impressions; branded queries span many URLs","Refresh and clarify brand-trust/support pages, and reduce overlap between /about and /faq/about","Improve branded journeys and reduce cannibalization","open","","2026-06-22","","","Brand navigational users hit multiple similar pages with unclear differentiation.","Sharper page roles help both CTR and downstream conversion journeys.","CTR +0.2-0.5pp; Bounce rate -3-6%","Separate company story, support entry points and pricing objections; cross-link intentionally instead of duplicating copy.","9","3","3","3","2","2","0.78"],
  ["2026-06-08","P2","Redirects","https://shopline.tw/","3XX and redirect chain","A small redirect set remains after the major cleanup","Site Audit: 3XX redirect 3, redirect chain 1","Clean the leftover redirects so link equity and crawl efficiency are not diluted","Reduce crawl waste and future regression risk","open","","2026-06-22","","","The redirect bucket is small now, which makes cleanup cheap and low risk.","Closing the remaining loop avoids future link/path regressions.","Broken links -80-100%; Crawl efficiency +2-5%","Map the 3XX URLs, replace internal links with final targets, and verify chain removal in the next crawl.","8","2","2","2","4","2","0.81"],
  ["2026-06-08","P2","Prune/Noindex","https://shopline.tw/news/","stale press releases","Some low-value news URLs hold no traffic and little strategic support value","Weak-link and sitemap-missing samples include several news pages with zero traffic","Prune, merge or noindex stale press assets that do not support trust, links or citations","Improve crawl focus and reduce maintenance noise","open","","2026-06-22","","","Old press pages consume crawl budget and internal-link opportunities without contributing demand.","Removing or deindexing low-value pages sharpens site focus.","Indexable pages +0-5; Crawl waste -10-20%","Review zero-traffic press pages, keep only those with authority or citation value, and noindex/archive the rest.","7","2","2","1","3","1","0.72"],
  ["2026-06-08","P2","Measurement","MCP_Config","GA4 key events","Native GA4 Organic Search key events are missing from this run","GA4 connector unavailable; only Ahrefs Web Analytics proxy sessions/users were available","Restore GA4 MCP and query generate_lead / purchase for the next report","Recover conversion visibility for SEO prioritization","open","","2026-06-22","","","Without native GA4 key events, prioritization still leans on traffic and intent rather than confirmed conversions.","Restoring GA4 closes the loop from SERP change to business result.","Key events +3-8%; Reporting confidence +20-40%","Reconnect GA4 MCP, validate organic channel filter, and store generate_lead/purchase summaries only.","9","4","2","5","1","3","0.93"],
  ["2026-06-08","P2","Monitoring","MCP_Config","Workduo competitors","Competitor AI citations are available, but pagination and negative-theme coverage remain shallow","Workduo competitor citations show cyberbiz.io, bvshop.tw, 91app.com and blog.easystore.co leading on several days; negative themes returned empty set","Expand Workduo competitor monitoring to daily rollups and theme slices","Keep AI search reporting comparable week to week","open","","2026-06-22","","","Current Workduo output is useful, but not yet deep enough for persistent topic-gap monitoring.","A stable monitoring layer improves GEO decision quality and follow-up speed.","AI visibility insights +10-20%; Reporting latency -20-30%","Persist daily platform/entity rollups, paginate citations, and add topic/theme segmentation when available.","8","3","2","2","2","1","0.76"]
];

const evidenceHeaders = [
  "run_id","evidence_id","source_tool","insight_type","page_url","keyword_or_topic","metric_summary","comparison","source_query","confidence","action_ref","created_at","evidence_date","report_title","source","category","entity","metric","value","evidence","implication","expected_outcome_range","module","priority_score"
];

const evidenceRows = [
  [runId,"E1","Ahrefs GSC pages","CTR gap","https://shopline.tw/online-store/features","網路開店功能","1,382 impressions, 0 clicks, CTR 0.00%, avg pos 1.25","High visibility with no clicks this week","gsc-pages high impression low ctr","0.88","A1","2026-06-08","2026-06-01/2026-06-07",reportTitle,"Ahrefs GSC","CTR","/online-store/features","ctr","0.00%","The page is ranking in premium positions but snippet response is effectively zero.","Prioritize snippet rewrite and richer SERP support blocks.","CTR +0.3-0.8pp","search_performance_summary","12"],
  [runId,"E2","Ahrefs GSC pages","CTR gap","https://shopline.tw/about","shopline是什麼","1,810 impressions, 7 clicks, CTR 0.39%, avg pos 1.43","About page still under-clicked while ranking near #1","gsc-pages current week","0.84","A1","2026-06-08","2026-06-01/2026-06-07",reportTitle,"Ahrefs GSC","CTR","/about","ctr","0.39%","Brand-trust intent is not being captured efficiently despite strong rankings.","Refresh company-story snippet and support cues.","CTR +0.2-0.5pp","executive_summary","12"],
  [runId,"E3","Ahrefs Site Audit","Technical","https://shopline.tw/about/pricing","slow page","Slow page issue count 22","Issue remains after major sitewide recovery","site-audit-page-explorer slow page","0.8","A3","2026-06-08","2026-06-02",reportTitle,"Ahrefs Site Audit","Technical","/about/pricing","slow_page","22 affected URLs","Speed is now a focused template issue rather than a sitewide fire.","A targeted performance sprint is likely to pay back quickly.","Organic sessions +3-6%","technical_seo_summary","12"],
  [runId,"E4","Ahrefs Site Audit","Internal linking","https://shopline.tw/ai","one dofollow incoming internal link","38 pages with only one dofollow incoming internal link","Strategic pages like /ai and crowdfunding are weakly linked","site-audit-page-explorer weak internal links","0.86","A4","2026-06-08","2026-06-02",reportTitle,"Ahrefs Site Audit","Internal Linking","/ai","incoming_internal_links","1","Important strategic pages lack internal authority.","Internal-link remediation should help discovery and indexation.","Indexable pages +5-10","internal_linking_summary","13"],
  [runId,"E5","Ahrefs Site Audit","Sitemap","https://shopline.tw/ai","indexable page not in sitemap","5 indexable pages missing from sitemap","Includes /ai and other strategic URLs","site-audit-page-explorer sitemap gap","0.84","A4","2026-06-08","2026-06-02",reportTitle,"Ahrefs Site Audit","Technical","/ai","sitemap_coverage","5 affected URLs","Crawl coverage is still incomplete for a small but important set of pages.","Fixing sitemap coverage is low-effort, high-leverage hygiene.","Indexable pages +5-10","technical_seo_summary","13"],
  [runId,"E6","Ahrefs Site Explorer","Competitor gap","https://www.cyberbiz.io/blog/fb貼文尺寸/","fb貼文尺寸, 免費圖片, reels是什麼","Cyberbiz has 3,502 TW keywords and 6,615 refdomains","Cyberbiz exceeds SHOPLINE keyword breadth by 1,047 keywords","batch-analysis + top pages","0.83","A5","2026-06-08","2026-06-07",reportTitle,"Ahrefs Site Explorer","Competitor","cyberbiz.io","org_keywords","3502","Competitor breadth comes from repeatable tutorial formats and utility content.","SHOPLINE needs comparison and how-to assets with clearer non-brand capture.","Organic sessions +8-15%","competitor_ai_summary","12"],
  [runId,"E7","Workduo AI","Citation share","https://shopline.tw/","owned vs competitor citations","shopline.tw citation share 2.24%-4.35%; cyberbiz.io and bvshop.tw out-cite on multiple days","Competitor citation domains often exceed owned domain share","workduo citations custom 2026-06-01..07","0.79","A7","2026-06-08","2026-06-01/2026-06-07",reportTitle,"Workduo","AI Search","shopline.tw","citation_share","owned trails leading competitor domains","The AI gap is sourceability, not visibility alone.","Create proof pages and FAQ assets designed for citation reuse.","AI citations +10-25%","competitor_ai_summary","10"],
  [runId,"E8","Ahrefs Web Analytics","Organic landing performance","https://shopline.tw/about/pricing","Organic Search landing quality","107 organic landing visitors, 109 entries, 510s avg session duration","Pricing attracts engaged search traffic despite weaker clicks","web-analytics-entry-pages search filter","0.81","A1","2026-06-08","2026-06-01/2026-06-07",reportTitle,"Ahrefs Web Analytics","Landing Page","/about/pricing","avg_session_duration_sec","510","This page is worth protecting and amplifying because post-click engagement is strong.","CTR improvements here should convert into quality sessions, not vanity traffic.","Organic sessions +5-10%","search_performance_summary","12"]
];

const runLogHeaders = [
  "run_id","run_datetime","period_start","period_end","source_tool","query_type","query_summary","limit","status","rows_returned","error_or_note"
];

const runLogs = [
  [runId,executedAt,periodStart,periodEnd,"Ahrefs GSC pages","page_performance","Top pages, high-impression low-CTR pages, sampled page deltas for TW","50","success","50","Current week data is materially lower than prior week on branded pages; used as observed, not normalized."],
  [runId,executedAt,periodStart,periodEnd,"Ahrefs GSC keywords","query_performance","Top queries, branded spread, sampled non-brand filters for TW","60","success","60","Non-brand current-week query sample is thin; supplemented with Site Explorer keyword intent data."],
  [runId,executedAt,periodStart,periodEnd,"Ahrefs GSC performance by position","position_buckets","Position-range distribution for TW","5","success","5","4-20 bucket still has impression opportunity but few clicks."],
  [runId,executedAt,periodStart,periodEnd,"Ahrefs Web Analytics source channels","organic_proxy","Organic Search users, visits, bounce and duration proxy","20","success","9","Used as GA4 fallback because native GA4 connector was unavailable."],
  [runId,executedAt,periodStart,periodEnd,"Ahrefs Web Analytics entry pages","organic_landing_pages","Top organic landing pages by visitors and entries","20","success","20","Supports landing-page quality analysis but does not replace GA4 key events."],
  [runId,executedAt,periodStart,periodEnd,"Ahrefs Site Audit","technical_summary","Latest project health + issues + sample URLs","173","success","173","Screaming Frog MCP unavailable; Ahrefs Site Audit used as technical fallback."],
  [runId,executedAt,periodStart,periodEnd,"Ahrefs Site Explorer","site_keyword_top_page","Organic keyword intent + top pages for SHOPLINE and competitors","40","success","40","91APP required apex-domain retry because www target returned zero traffic in initial batch."],
  [runId,executedAt,periodStart,periodEnd,"Ahrefs batch analysis","competitor_snapshot","Traffic, keywords, backlinks and refdomains across SHOPLINE + 5 competitors","6","success","6","Used for comparable competitor benchmark rows."],
  [runId,executedAt,periodStart,periodEnd,"Workduo metrics","ai_visibility","Platform/entity visibility, SOV, mentions, position for owned + competitors","20","success","20","Negative theme API returned no rows this week; main insight comes from visibility and citations."],
  [runId,executedAt,periodStart,periodEnd,"Workduo citations","ai_citations","Owned and competitor domain citation share","20","success","20","Initial competitor citation call timed out once; retry succeeded with narrower filter."],
  [runId,executedAt,periodStart,periodEnd,"GA4 MCP","organic_conversions","Organic Search users, key events, revenue","0","warning","0","Native GA4 connector unavailable in current run; keyEvents not included in validation."]
];

const payload = {
  outPath,
  weeklyHeaders,
  weeklyRow,
  actionHeaders,
  actions,
  evidenceHeaders,
  evidenceRows,
  runLogHeaders,
  runLogs,
};

async function buildWorkbook() {
  const { SpreadsheetFile, Workbook } = await import("@oai/artifact-tool");
  const wb = Workbook.create();
  const weekly = wb.worksheets.add("Weekly_Report");
  const actionsWs = wb.worksheets.add("SEO_Actions");
  const evidenceWs = wb.worksheets.add("Insight_Evidence");
  const logWs = wb.worksheets.add("MCP_Run_Log");

  for (const ws of [weekly, actionsWs, evidenceWs, logWs]) {
    ws.showGridLines = false;
  }

  weekly.getRange(`A1:AG1`).values = [weeklyHeaders];
  weekly.getRange(`A2:AG2`).values = [weeklyRow];
  actionsWs.getRange(`A1:Y1`).values = [actionHeaders];
  actionsWs.getRange(`A2:Y${actions.length + 1}`).values = actions;
  evidenceWs.getRange(`A1:X1`).values = [evidenceHeaders];
  evidenceWs.getRange(`A2:X${evidenceRows.length + 1}`).values = evidenceRows;
  logWs.getRange(`A1:K1`).values = [runLogHeaders];
  logWs.getRange(`A2:K${runLogs.length + 1}`).values = runLogs;

  const xlsx = await SpreadsheetFile.exportXlsx(wb);
  await xlsx.save(outPath);
}

await fs.mkdir(outDir, { recursive: true });
if (process.argv.includes("--json")) {
  console.log(JSON.stringify(payload));
} else {
  await buildWorkbook();
  console.log(outPath);
}
